### ISSUE TITLE
Method signature of 'verifyIdToken' in Auth module does not match firebase-admin

### ISSUE THREAD

**Issue by mikesive** [freetrade-io/ts-firebase-driver-testing#84]
## Description
The method signature of `verifyTokenId` in the inProcessAuth module does not match the real deal:
firebase-admin:
https://github.com/firebase/firebase-admin-node/blob/master/src/auth/auth.ts#L176

ts-firebase-driver-testing:
https://github.com/freetrade-io/ts-firebase-driver-testing/blob/master/src/driver/Auth/FirebaseAuth.ts#L47

This makes it necessary to import firebase-admin rather than the inProcessFirebase when using this method.

**Comment by hughgrigg** [comment]
@mikesive thanks, can you make a PR to fix it?

**Comment by mikesive** [comment]
@hughgrigg already done :) https://github.com/freetrade-io/ts-firebase-driver-testing/pull/85
I just forgot to close the issue.
